In [1]:
import pandas as pd
df = pd.read_csv('your/path/RBD_valid_nucleotides_million.csv')

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
df.head()

,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein
0,EPI_ISL_3197453,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...
1,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein
2,EPI_ISL_16973626,BA.5.2.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...
3,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein
4,EPI_ISL_2090530,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...

In [3]:
df = df[df['Accession ID'].str.startswith('EPI_')]

In [4]:
df.head()

,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein
0,EPI_ISL_3197453,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...
2,EPI_ISL_16973626,BA.5.2.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...
4,EPI_ISL_2090530,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...
6,EPI_ISL_13391748,BA.2,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...
8,EPI_ISL_14789048,BA.5.2,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...

In [5]:
df.loc[:, 'Variant'] = df['Variant'].replace('Not a VOC', 'nonVOC')

In [7]:
df.to_csv('your/path/RBD_valid_nucleotides.csv', index=False)

In [6]:
if df['RBD nucleotide'].str.contains('N').any():
    print("There is at least one 'N' in the 'RBD nucleotide' column.")
else:
    print("No 'N' found in the 'RBD nucleotide' column.")

No 'N' found in the 'RBD nucleotide' column.

In [10]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("your/path/RBD_valid_nucleotides.csv")

# Count the number of rows for each unique value in the "Lineage" column
lineage_counts = df['Lineage'].value_counts()

# Print the counts
print(lineage_counts)

Lineage
B.1.1.7      118481
BA.2          67107
AY.4          50307
BA.1.1        48689
BA.2.12.1     25196
              ...
B.1.1.361         1
EP.1.1            1
B.1.1.265         1
B.1.1.112         1
B.1.250           1
Name: count, Length: 3155, dtype: int64

In [11]:
df.loc[df["Accession ID"]=="EPI_ISL_402124"]

,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein
0,EPI_ISL_402124,A.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,WuhanHu1,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...

In [46]:
# creating sample subset for testing:
df = pd.read_csv('your/path/RBD_valid_nucleotides.csv')
subset_df = df.head(1000)
subset_df.to_csv('subset_df.csv', index=False)

In [47]:
lineage_counts = subset_df['Lineage'].value_counts()

# Print the counts
print(lineage_counts)

Lineage
B.1.1.7      110
BA.2          66
BA.1.1        50
AY.4          43
B.1.617.2     24
            ...
BA.5.2.20      1
BA.5.9         1
BA.2.3.17      1
BF.21          1
AY.93          1
Name: count, Length: 263, dtype: int64

,Virus name,Last vaccinated,Passage details/history,Type,Accession ID,Collection date,Location,Additional location information,Sequence length,Host,...,Pango version,Variant,AA Substitutions,Submission date,Is reference?,Is complete?,Is high coverage?,Is low coverage?,N-Content,GC-Content
0,hCoV-19/India/KA-RFNB-6196/2022,NaN,Original,betacoronavirus,EPI_ISL_10746595,2022-02,Asia / India / Karnataka,NaN,29884,Human,...,consensus call,Former VOC Omicron GRA (B.1.1.529+BA.*) first ...,"(NSP5_P132H,NSP3_G489S,NSP4_T327I,Spike_S373P,...",2022-03-07,NaN,True,NaN,NaN,NaN,0.378998795342
1,hCoV-19/India/KA-RFNB-6116/2022,NaN,Original,betacoronavirus,EPI_ISL_10746594,2022-02,Asia / India / Karnataka,NaN,29884,Human,...,consensus call,Former VOC Omicron GRA (B.1.1.529+BA.*) first ...,"(NSP5_P132H,Spike_S371F,NSP3_G489S,NSP13_R392C...",2022-03-07,NaN,True,NaN,NaN,NaN,0.379166108955
2,hCoV-19/India/KA-RFNB-6166/2022,NaN,Original,betacoronavirus,EPI_ISL_10746593,2022-02,Asia / India / Karnataka,NaN,29902,Human,...,consensus call,Former VOC Omicron GRA (B.1.1.529+BA.*) first ...,"(NSP5_P132H,Spike_S371F,NSP3_G489S,NSP13_R392C...",2022-03-07,NaN,True,NaN,NaN,NaN,0.3792388469
3,hCoV-19/India/KA-RFNB-6141/2022,NaN,Original,betacoronavirus,EPI_ISL_10746592,2022-02,Asia / India / Karnataka,NaN,29884,Human,...,consensus call,Former VOC Omicron GRA (B.1.1.529+BA.*) first ...,"(NSP5_P132H,NSP3_G489S,NSP13_R392C,Spike_K417N...",2022-03-07,NaN,True,NaN,NaN,NaN,0.379032258065
4,hCoV-19/India/KA-RFNB-6175/2022,NaN,Original,betacoronavirus,EPI_ISL_10746591,2022-02,Asia / India / Karnataka,NaN,29893,Human,...,consensus call,Former VOC Omicron GRA (B.1.1.529+BA.*) first ...,"(NSP5_P132H,NSP3_G489S,NSP4_T327I,Spike_S373P,...",2022-03-07,NaN,True,NaN,NaN,NaN,0.379051951962

In [15]:
# Python script that will take in csv file that contains RBD nuc sequences and protein sequences to compare 
# Accession ID values with metadata.tsv to access Collection date value for each row and divide each Lineage 
# group into 10 Generations unique to the lineage based on Collection date range

import pandas as pd

# Load the CSV files
# metadata_df = pd.read_csv("metadata.tsv", sep='\t', dtype=str, low_memory=False, encoding='latin-1')
nuc_prot_df = pd.read_csv("your/path/RBD_valid_nucleotides.csv")

# Merge the two dataframes on Accession ID
merged_df = nuc_prot_df.merge(metadata_df[['Accession ID', 'Collection date']], on='Accession ID', how='left')

In [18]:
merged_df.loc[merged_df["Accession ID"]=="EPI_ISL_402124"]

,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein,Collection date
0,EPI_ISL_402124,A.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,WuhanHu1,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...,2019-12-30

In [16]:
merged_df.head()

,Accession ID,Lineage,RBD nucleotide,Variant,RBD protein,Collection date
0,EPI_ISL_402124,A.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,WuhanHu1,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...,2019-12-30
1,EPI_ISL_3197453,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...,2021-04-28
2,EPI_ISL_16973626,BA.5.2.1,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...,2023-02-01
3,EPI_ISL_2090530,B.1.1.7,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,alpha,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...,2021-04-25
4,EPI_ISL_13391748,BA.2,AGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAA...,omicron,RVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVAD...,2022-02

In [17]:
# Convert Collection date to %Y-%m-%d format
merged_df['Collection date'] = pd.to_datetime(merged_df['Collection date'], format='%Y-%m-%d', errors='coerce')
merged_df['Collection date'] = merged_df['Collection date'].dt.strftime('%Y-%m-%d')

# Filter rows with Collection date after November 2019
merged_df['Collection date'] = pd.to_datetime(merged_df['Collection date'])
merged_df = merged_df[merged_df['Collection date'] >= '2019-11-01']

# Group data by Lineage
grouped_data = merged_df.groupby('Lineage')

# Define a function to calculate 'Generation' for each Lineage group
def assign_generation(group):
    date_range = group['Collection date'].max() - group['Collection date'].min()
    bin_size = date_range / 10
    group['Generation'] = pd.cut(group['Collection date'], bins=10, labels=['Gen1', 'Gen2', 'Gen3', 'Gen4', 'Gen5', 'Gen6', 'Gen7', 'Gen8', 'Gen9', 'Gen10'])
    return group


# Filter Lineage groups with more than 10 sequences
filtered_groups = [group for name, group in grouped_data if len(group) > 6]

# Apply the assign_generation function to each filtered Lineage group
processed_data = pd.concat([assign_generation(group) for group in filtered_groups])

# Save the updated data to a new CSV file
output_csv = "your/path/RBD_valid_Gen.csv"
processed_data.to_csv(output_csv, index=False)

print(f"Output CSV file saved as {output_csv}")

Output CSV file saved as RBD_valid_Gen.csv

In [80]:
processed_data.head()

,Accession ID,Lineage,RBD nucleotide,RBD protein,Variant,Collection date,Generation,Dateframe
124,EPI_ISL_411956,A,AATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCT...,NGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIV...,WuhanHu1,2020-02-11,Gen1,Dateframe1
211,EPI_ISL_520744,A,AATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCT...,NGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIV...,WuhanHu1,2020-04-21,Gen2,Dateframe2
724,EPI_ISL_17682083,A,AATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCT...,NGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIV...,WuhanHu1,2020-06-22,Gen2,Dateframe2
6942,EPI_ISL_776445,A,AATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCT...,NGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIV...,WuhanHu1,2020-03-28,Gen1,Dateframe1
7759,EPI_ISL_901221,A,AATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCT...,NGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIV...,WuhanHu1,2020-03-09,Gen1,Dateframe1

In [77]:
import pandas as pd

# Load the RBD_valid_Gen.csv file
input_file = "your/path/RBD_valid_Gen.csv"
df = pd.read_csv(input_file)

# Subset the DataFrame to contain only rows with "BA.1" in the "Variant" column
subset_df = df[df["Lineage"] == "BA.1"]
subset_df.to_csv('your/path/subset.csv', index=False)

In [20]:
import pandas as pd

# Load the input CSV file
input_file = "your/path/RBD_valid_Gen.csv"
df = pd.read_csv(input_file)

# Initialize an empty list to store DataFrames
output_dfs = []

# Group the data by Lineage
grouped = df.groupby("Lineage")

# Iterate through each Lineage group
for lineage, group in grouped:
    generations = group["Generation"].unique()
    generations = sorted([int(gen.replace("Gen", "")) for gen in generations])  # Extract and convert to int

    # Filter for consecutive Generation values
    for i in range(len(generations) - 1):
        gen1, gen2 = generations[i], generations[i + 1]
        if abs(gen2 - gen1) == 1:
            # Get the rows with Generation values gen1 and gen2
            rows_gen1 = group[group["Generation"] == f"Gen{gen1}"]
            rows_gen2 = group[group["Generation"] == f"Gen{gen2}"]

            # Check if there are rows for the specified generations
            if not rows_gen1.empty and not rows_gen2.empty:
                # Create a new DataFrame for the output
                min_len = min(len(rows_gen1), len(rows_gen2))
                new_df = pd.DataFrame({
                    "Lineage": [lineage] * min_len,
                    "GenS1": [f"Gen{gen1}"] * min_len,
                    "GenS2": [f"Gen{gen2}"] * min_len,
                    
                    #"Seq1": rows_gen1["RBD protein"].values[:min_len],
                    #"Seq2": rows_gen2["RBD protein"].values[:min_len],

                    "Seq1": rows_gen1["RBD nucleotide"].values[:min_len],
                    "Seq2": rows_gen2["RBD nucleotide"].values[:min_len],
                    "Variant": rows_gen1["Variant"].values[:min_len],
                })

                # Append the new DataFrame to the list
                output_dfs.append(new_df)

# Concatenate all DataFrames in the list into one output DataFrame
output_df = pd.concat(output_dfs, ignore_index=True)

# Save the output DataFrame to a CSV file
#output_file = "RBD_valid_finetuning_proteins.csv"
output_file = "your/path/RBD_valid_finetuning_nucleotides.csv"
output_df.to_csv(output_file, index=False)